[tool.black]
line-length = 100
target-version = ["py310","py311"]

[tool.isort]
profile = "black"
line_length = 100

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["tests"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
strict = false

- name: mypy (type check)
  run: mypy . || true
