name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies (si existen)
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    - name: Run tests or smoke check (repo raíz)
      run: |
        if [ -d tests ] && compgen -G "tests/*.py" > /dev/null; then
          pytest -q
        else
          python - <<'PY'
print("root: smoke check OK")
PY
        fi
