name: Quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements-dev.txt

      # --- Formato automático ---
      - name: Black (autoformat)
        run: black .

      - name: isort (auto order)
        run: isort .

      # --- Verificación después del autoformato ---
      - name: Black (verify)
        run: black --check .

      - name: isort (verify)
        run: isort --check-only .

      - name: Flake8 (lint)
        run: flake8 .

      - name: mypy (type check)
        run: mypy .

      - name: Pytest
        run: pytest --cov=./ --cov-report=term-missing

      # --- Auto-commit de cambios de formato en main ---
      - name: Commit formatted code
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(format): apply black + isort"
          branch: main
