name: Quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements-dev.txt

      # Formato y estilo (si quieres tolerante pon "|| true" al final)
      - name: Black (format check)
        run: black --check .

      - name: isort (imports order)
        run: isort --check-only .

      - name: Flake8 (lint)
        run: flake8 .

      # Tipado (opcional, pero pro)
      - name: mypy (type check)
        run: mypy .

      # Tests
      - name: Pytest
        run: pytest --cov=./ --cov-report=term-missing
