name: Quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 mypy pytest pytest-cov

      # ---------- Chequeos (tolerantes) ----------
      - name: Flake8 (lint, tolerant)
        run: flake8 . || true

      - name: mypy (type check, tolerant)
        run: mypy . || true

      # ---------- Tests + Cobertura ----------
      - name: Pytest with coverage (XML)
        run: pytest --maxfail=0 --cov=sim --cov-report=xml:coverage.xml --cov-report=term-missing -q || true

      - name: Upload coverage.xml artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.python-version }}
          path: coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unittests,py${{ matrix.python-version }}
          slug: Mag0de0z2099/LPQM
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
