name: Quality

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements-dev.txt

      # Autoformato (no falla el job)
      - name: Black (autoformat)
        run: black .

      - name: isort (auto order)
        run: isort .

      # Guardar formateo en main (opcional)
      - name: Commit formatted code
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(format): apply black + isort"
          branch: main

      # Chequeos en modo NO bloqueante por ahora
      - name: Flake8 (lint, tolerant)
        run: flake8 . || true

      - name: mypy (type check, tolerant)
        run: mypy . || true

      - name: Pytest
        run: pytest -q
