name: Quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy pytest pytest-cov
      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # ---- Lint ----
      - name: Flake8 (lint, tolerant)
        run: flake8 . || true

      # ---- Type check ----
      - name: mypy (type check, tolerant)
        run: mypy . || true

      # ---- Tests + Cobertura ----
      - name: Run tests with coverage (XML)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest --maxfail=0 \
                 --cov=sim \
                 --cov-report=xml:coverage.xml \
                 --cov-report=term-missing \
                 --cov-fail-under=30 \
                 -q

      # ---- Subir coverage como artefacto ----
      - name: Upload coverage XML as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.python-version }}
          path: coverage.xml

      # ---- Subir a Codecov (no bloquea si falla) ----
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests,py${{ matrix.python-version }}
          slug: Mag0de0z2099/LPQM
          fail_ci_if_error: false
