name: CI - simulador

on:
  push:
    branches: [ "main" ]
    paths: [ "simulador/**", ".github/workflows/simulador-ci.yml", "requirements.txt" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "simulador/**", ".github/workflows/simulador-ci.yml", "requirements.txt" ]

permissions:
  contents: read

concurrency:
  group: simulador-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies (root if exists)
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f simulador/requirements.txt ]; then pip install -r simulador/requirements.txt; fi
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests or smoke check (simulador)
      working-directory: simulador
      run: |
        if [ -d tests ] && compgen -G "tests/*.py" > /dev/null; then
          pytest -q
        else
          python - <<'PY'
print("simulador: smoke check OK")
PY
        fi
